# REST style

@baseUrl = http://{{host}}:{{nginxPublishedPort}}/api/v1
@createUserUrl = {{baseUrl}}/user

POST {{createUserUrl}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "createUser": {
    "firstName": "Иван",
    "lastName": "Иванов",
    "email": "i.ivanov@gmail.com",
    "birthDate": "2005-03-05"
  }
}
