# REST style

@baseUrl = http://{{host}}:{{nginxPublishedPort}}/api/v1
@getUserUrl = {{baseUrl}}/user?id=11

GET {{getUserUrl}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
