# REST style

@baseUrl = http://{{host}}:{{nginxPublishedPort}}/api/v1
@updateUserEmailUrl = {{baseUrl}}/user/email?id=14

PATCH {{updateUserEmailUrl}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "newEmail": "i.ivanov@mail.ru"
}
