POST http://localhost:{{nginxPublishedPort}}/event/add
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "event": {
    "id": 2,
    "name": "event_2",
    "priority": 2000,
    "conditions": {
      "param1": 2,
      "param2": 2
    }
  }
}
