POST http://localhost:{{nginxPublishedPort}}/api/v1/event/add
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "event": {
    "id": 3,
    "name": "event_3",
    "priority": 3000,
    "conditions": {
      "param1": 1,
      "param2": 2
    }
  }
}
