# REST style

@baseUrl = http://{{host}}:{{nginxPublishedPort}}/api/v1
@getEventUrl = {{baseUrl}}/event

GET {{getEventUrl}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "params": {
    "param1": 1,
    "param2": 2
  }
}
