
# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
    #Контейнер с PHP, назовём его app
    php-fpm:
        # Если нет секции build, то система будет искать образ в репозиториях
        build:
            context: ./docker/fpm
            dockerfile: Dockerfile
        user: "${CUR_UID:-1000}:${CUR_GID:-1000}"
        volumes:
            - ./app:/data/application.local
            - php_socket:/var/run/php
        networks:
            - app-network

    #контейне с Nginx
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                UID: ${CUR_UID}
                GID: ${CUR_GID}
        user: "${CUR_UID:-1000}:${CUR_GID:-1000}"
        ports:
            - "${HTTP_PORT:-8080}:8080" 
            - "${HTTPS_PORT:-8443}:8443"
        volumes:
            - ./app:/data/application.local
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - php_socket:/var/run/php
        networks:
            - app-network
    postgres:
        image: ${POSTGRES_IMAGE:-postgres:12.4-alpine}  # Используем переменную из .env
        user: "postgres:postgres"
        container_name: ${POSTGRES_HOST:-postgres}
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-hw1_database}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            # Дополнительные настройки для производительности
            POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data  # Постоянное хранение данных
        networks:
            - app-network
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: 512M
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB:-hw1_database}"]
            interval: 10s
            timeout: 5s
            retries: 5
    memcached:
        build:
            context: ./docker/memcached
        user: "memcache"
        networks: 
            - app-network
        # БЕЗОПАСНОСТЬ: -m 512 ограничивает использование RAM внутри процесса
        command: '-m 512'
        deploy:
            resources:
                limits:
                    memory: 600M
    redis:
        build:
            context: ./docker/redis
            args:
                redis_image: ${REDIS_IMAGE:-redis:alpine}
        # Используем твой UID 1000
        user: "redis"
        networks: 
            - app-network
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
        deploy:
            resources:
                limits:
                    memory: 300M
#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
    php_socket:
