---
config:
  theme: redux-color
---
erDiagram
	direction TB
	SESSION {
		bigserial id PK ""
		bigserial movie_id FK ""
		bigserial order_id FK ""
		smallserial hall_id FK ""
		timestamp start_time  ""
	}

	HALL-CATEGORY {
		enum category PK ""
		money price  ""
	}

	ORDER {
		bigserial id PK ""
		bigint customer_id FK ""
		bigint session_id FK ""
		integer place_id FK ""
		timestamp time  ""
	}

	PLACE {
		serial id PK ""
		smallint hall_id FK ""
		smallint cinema-id FK ""
		smallint row  ""
		smallint place  ""
		enum category FK ""
	}

	HALL {
		smallserial id PK ""
		smallint cinema-id FK ""
		smallint number  ""
	}

	CINEMA {
		smallserial id PK ""
		character-varying city  ""
		text address  ""
	}

	CUSTOMER {
		bigserial id  ""
		character-varying name  ""
		character-varying email  ""
		character-varying phone  ""
	}

	MOVIE {
		bigserial id PK ""
		character-varying name  ""
	}

	HALL-CATEGORY}|--|{PLACE:"  "
	HALL||--|{PLACE:"  "
	ORDER}|--|{CUSTOMER:"  "
	SESSION||--|{ORDER:"  "
	MOVIE||--|{SESSION:"  "
	SESSION}|--||HALL:"  "
	ORDER}|--|{PLACE:"  "
	CINEMA||--|{HALL:"  "