---
config:
  theme: redux-color
---
erDiagram
	direction TB
	CINEMA {
		smallserial id PK ""
		string city  ""
		string address  ""
	}

	CUSTOMER {
		bigserial id  ""
		string name  ""
		string email  ""
		string phone  ""
	}

	MOVIE {
		bigserial id PK ""
		string name  ""
	}

	SESSION {
		bigserial id PK ""
		bigserial movie_id FK ""
		bigserial order_id FK ""
		smallserial hall_id FK ""
		timestamp start_time  ""
	}

	HALL-CATEGORY {
		enum category PK ""
		money price  ""
	}

	ORDER {
		bigserial id PK ""
		bigserial customer_id FK ""
		bigserial session_id FK ""
		integer place_id  ""
		timestamp time  ""
	}

	HALL {
		smallserial id PK ""
		smallserial cinema-id FK ""
		smallserial number  ""
	}

	PLACE {
		integer id PK ""
		smallserial hall_id FK ""
		smallserial cinema-id FK ""
		smallserial row  ""
		smallserial place  ""
		enum category FK ""
	}

	HALL-CATEGORY}|--|{PLACE:"  "
	HALL||--|{PLACE:"  "
	ORDER}|--|{CUSTOMER:"  "
	SESSION||--|{ORDER:"  "
	MOVIE||--|{SESSION:"  "
	SESSION}|--||HALL:"  "
	ORDER}|--|{PLACE:"  "
	CINEMA||--|{HALL:"  "