---
config:
  theme: redux-color
  layout: dagre
---
erDiagram
	direction TB
	SESSION {
		bigserial id PK ""
		bigserial movie_id FK ""
		bigserial order_id FK ""
		smallserial hall_id FK ""
		timestamp start_time  ""
	}

	ORDER {
		bigserial id PK ""
		bigint customer_id FK ""
		bigint session_id FK ""
		integer place_id FK ""
		timestamp time  ""
	}

	HALL {
		smallserial id PK ""
		smallint cinema-id FK ""
		smallint number  ""
	}

	CINEMA {
		smallserial id PK ""
		character-varying city  ""
		text address  ""
	}

	CUSTOMER {
		bigserial id  ""
		character-varying name  ""
		character-varying email  ""
		character-varying phone  ""
	}

	MOVIE {
		bigserial id PK ""
		character-varying name  ""
	}

	PLACE {
		serial id PK ""
		smallint hall_id FK ""
		smallint cinema-id FK ""
		smallint category_id FK ""
		bigint price_id FK ""
		smallint row  ""
		smallint place  ""
	}

	PLACE-CATEGORY {
		smallserial id PK ""
		enum location  "'в центре', 'с краю', 'в центре, далеко', 'с краю далеко'"
	}

	PART-OF-DAY {
		small-int id PK ""
		enum value  "Утро, день, вечер, ночь"
	}

	PRICE {
		bigserial id PK ""
		bigint move-id FK ""
		bigint place-category-id FK ""
		smallint part-of-day-id FK ""
		money price  ""
	}

	PLACE-CATEGORY}|--|{PLACE:"  "
	HALL||--|{PLACE:"  "
	ORDER}|--|{CUSTOMER:"  "
	SESSION||--|{ORDER:"  "
	MOVIE||--|{SESSION:"  "
	SESSION}|--||HALL:"  "
	ORDER}|--|{PLACE:"  "
	CINEMA||--|{HALL:"  "
	PRICE}|--|{PLACE-CATEGORY:"  "
	PRICE}|--|{PLACE:"  "
	PART-OF-DAY}|--|{PRICE:"  "
	MOVIE||--|{PRICE:"  "