CREATE TABLE movies (
    ID BIGINT PRIMARY KEY,
    TITLE NVARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    GLOBAL_RELEASE_DATE DATE NOT NULL,
    GLOBAL_END_DATE DATE,
    DURATION_MINUTES INTEGER NOT NULL,
    BASE_COST NUMERIC NOT NULL,
    AGE_RESTRICTION INTEGER
);

CREATE TABLE customers (
    ID INTEGER PRIMARY KEY,
    FIRST_NAME NVARCHAR(100) NOT NULL,
    SURNAME NVARCHAR(100) NOT NULL,
    MAIL VARCHAR(255),
    PHONE VARCHAR(20)
);

CREATE TABLE hals (
    ID BIGINT PRIMARY KEY,
    HALS_NAME NVARCHAR(100) NOT NULL UNIQUE,
    CAPACITY INTEGER NOT NULL,
    AMOUNT_ROW INTEGER NOT NULL,
    COST_MODIFIER INTEGER NOT NULL
);

CREATE TABLE places (
    ID INTEGER PRIMARY KEY,
    HALS_ID INTEGER NOT NULL,
    ROW_ID INTEGER NOT NULL,
    POSITION INTEGER NOT NULL,
    COST_MODIFIER INTEGER NOT NULL,
    FOREIGN KEY (HALS_ID) REFERENCES hals(ID)
);

CREATE TABLE movie_sessions (
    ID BIGINT PRIMARY KEY,
    MOVIES_ID INTEGER NOT NULL,
    HALS_ID INTEGER NOT NULL,
    START_SESSION TIMESTAMP NOT NULL,
    END_SESSION TIMESTAMP NOT NULL,
    COST_MODIFIER INTEGER NOT NULL,
    FOREIGN KEY (MOVIES_ID) REFERENCES movies(ID),
    FOREIGN KEY (HALS_ID) REFERENCES hals(ID)
);

CREATE TABLE tickets (
    ID BIGINT PRIMARY KEY,
    CLIENT_ID BIGINT NOT NULL,
    SESSION_ID BIGINT NOT NULL,
    TICKET_COST NUMERIC NOT NULL,
    TIME_OF_BUY TIMESTAMP NOT NULL,
    PLACE_ID BIGINT NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES customers(ID),
    FOREIGN KEY (SESSION_ID) REFERENCES movie_sessions(ID),
    FOREIGN KEY (PLACE_ID) REFERENCES places(ID)
);
