services:
  franken:
    build:
      dockerfile: ./docker/franken/Dockerfile
    volumes:
      - ./app/:/var/www/html/app
      - ./docker/franken/config/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "8080:80"

  rabbitmq:
    image: rabbitmq:3.7.3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
