services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
       - ./html:/var/www/html
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
    restart: always
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_HOST_PORT
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
