services:

    application:
        build:
            context: .
            dockerfile: Dockerfile
            target: compose
            args:
                UID: ${UID}
                GID: ${GID}
        command:
            - php
            - bin/console.php
            - run
        depends_on:
            - redis
            - memcached
        volumes:
            - ./html:/var/www/html:rw
        networks:
            private:

    redis:
        image: valkey/valkey:9.0-trixie
        networks:
            private:

    memcached:
        image: memcached:1.6-trixie
        networks:
            private:

networks:
    private:
        name: otus-php-2025
        driver: bridge
