version: '3.8'

services:

  db:
    image: postgres
    container_name: postgres_service2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    networks:
      - postgres

networks:
    postgres:
volumes:
    postgresql_data:
