
services:
 #Контейнер с nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: nginx
    ports:
      - "80:8080"
    networks:
      - app-network
    volumes:
       - ./code:/data/mysite.local

  #Контейнер с PHP-FPM
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php 
    container_name: app 
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

#виртуальная сеть
networks:
  app-network:
    driver: bridge