version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./project:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./project/.env:/var/www/html/.env
    env_file:
      - ./project/.env

    expose:
      - 9000

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
