services:

  manager_php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    volumes:
      - ./app:/app:rw
    depends_on:
      elasticsearch:
        condition: service_started
    working_dir: /app
    networks:
      - app-network
    env_file: .env


  manager_nginx_main:
    image: nginx:1.25.4
    volumes:
      - ./app:/app:rw
      - ./docker/nginx_main/logs:/var/log/nginx:rw
      - ./docker/nginx_main/hosts:/etc/nginx/conf.d
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      manager_php-fpm:
        condition: service_started
    env_file: .env

  elasticsearch:
    container_name: ${ELASTIC_CONTAINER_NAME}
    image: elasticsearch:8.17.4
    volumes:
      - ./docker/elasticsearch/config.yaml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    networks:
      - app-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 4GB
    env_file: .env

networks:
  app-network:
    driver: bridge
