services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balance/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
       - ./html:/var/www/html
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
    restart: always
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_HOST_PORT
    networks:
      - app-network
      
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - app-network

  phpunit:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: phpunit --configuration phpunit.xml
    networks:
      - app-network
    depends_on:
      - php-fpm
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network   
      
networks:
  app-network:
    driver: bridge
