services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: ${CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./code:/data/mysite.local
      - php_socket:/var/run/php-fpm.sock
    depends_on:
      - app
      - postgres
    networks:
      - app-network

  app:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./code:/data/mysite.local
      - php_socket:/var/run/php-fpm.sock
    env_file:
      - ${ENV_FILE}
    networks:
      - app-network

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: myapp/redis
    container_name: app_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  memcached:
    image: memcached
    container_name: app_memcached
    ports:
      - "${MEMCACHED_PORT}:11211"
    command: [ "memcached", "-m", "64", "-l", "0.0.0.0" ]
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  php_socket:
  redis_data:
  postgres_data:
