services:

  manager_php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    ports:
      - '9000:9000'
    volumes:
      - ./app:/app:rw
    depends_on:
      manager_redis:
        condition: service_started
      manager_memcached:
        condition: service_started
    working_dir: /app

  manager_nginx:
    image: nginx:1.25.4
    depends_on:
      - manager_php-fpm
    volumes:
      - ./app:/app:rw
      - ./docker/nginx/logs:/var/log/nginx:rw
      - ./docker/nginx/hosts:/etc/nginx/conf.d
    ports:
      - '80:80'

  manager_redis:
    image: redis:7.2.1
    restart: always

  manager_memcached:
    image: memcached:1.6.34
    restart: always
