version: '1.0.1'

name: 'PHP 2025 homework'

services:
  nginx_balancer:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: balance/nginx_balancer
    container_name: nginx_balancer
    ports:
      - "80:80"
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - nginx_1
      - nginx_2
    networks:
      - app-network

  nginx_1:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: balance/nginx_1
    container_name: nginx_1
    volumes:
      - './public:/var/www/public'
      - './app:/var/www/app'
      - './composer/vendor:/var/www/composer/vendor'
      - './docker/nginx/mysite.local.conf:/etc/nginx/conf.d/mysite.local.conf'
    depends_on:
      - php_fpm_1
      - php_fpm_2
    networks:
      - app-network

  nginx_2:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: balance/nginx_2
    container_name: nginx_2
    volumes:
      - './public:/var/www/public'
      - './app:/var/www/app'
      - './composer/vendor:/var/www/composer/vendor'
      - './docker/nginx/mysite.local.conf:/etc/nginx/conf.d/mysite.local.conf'
    depends_on:
      - php_fpm_1
      - php_fpm_2
    networks:
      - app-network

  php_fpm_1:
    build:
      context: docker/fpm
      dockerfile: Dockerfile
    image: balance/php_fpm_1
    container_name: php_fpm_1
    volumes:
      - './public:/var/www/public'
      - './app:/var/www/app'
      - './composer/vendor:/var/www/composer/vendor'
    restart: always
    environment:
      - REDIS_HOST
      - REDIS_HOST_PORT
    networks:
      - app-network

  php_fpm_2:
    build:
      context: docker/fpm
      dockerfile: Dockerfile
    image: balance/php_fpm_2
    container_name: php_fpm_2
    volumes:
      - './public:/var/www/public'
      - './app:/var/www/app'
      - './composer/vendor:/var/www/composer/vendor'
    restart: always
    environment:
      - REDIS_HOST
      - REDIS_HOST_PORT
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_HOST
      - REDIS_HOST_PORT
      - ALLOW_EMPTY_PASSWORD
    networks:
      - app-network

networks:
  app-network:
    driver: bridge