# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: "${CONTAINER_NAME}"
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local

  #Контейнер с PHP-FPM
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: php:8.4-fpm
    container_name: php-fpm
    volumes:
      - ./code:/data/mysite.local
    depends_on:
      - nginx

  #Контейнер с redis
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./code:/data/mysite.local

  #Контейнер с memcached
  memcached:
    build:
      context: ./memcached
      dockerfile: Dockerfile
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"

  #Контейнер с postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres
    container_name: postgres
    ports:
      - "8080:8080"