services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm-2

  php-fpm-1:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm-1
    volumes:
      - ./:/var/www
    depends_on:
      - redis-node-1

  php-fpm-2:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm-2
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm-1

  redis-node-1:
    image: redis
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-2:
    image: redis
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-3:
    image: redis
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-4:
    image: redis
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-5:
    image: redis
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-6:
    image: redis
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-cluster-setup:
    image: redis
    container_name: redis-cluster-setup
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint: >
      sh -c "
      echo 'Waiting for Redis nodes to be ready...' && sleep 5 &&
      echo 'Creating Redis cluster...' &&
      redis-cli -p 6379 --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1 --cluster-yes &&
      echo 'Redis cluster created successfully!' &&
      tail -f /dev/null
      "