version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Nginx.Dockerfile
    image: balance/nginx
    container_name: balancer-nginx
    ports:
      - "8096:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/app
  fpm1:
    build:
      context: .
      dockerfile: ./docker/php/Fpm.Dockerfile
    image: balance/php
    container_name: fpm1
    volumes:
      - ./:/var/www/app
    networks:
      - internal
      - fpm-redis-1
  redis1:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data/redis
    networks:
      - internal
      - fpm-redis-1
  fpm2:
    build:
      context: .
      dockerfile: ./docker/php/Fpm.Dockerfile
    image: balance/php
    container_name: fpm2
    volumes:
      - ./:/var/www/app
    networks:
      - internal
      - fpm-redis-2
  redis2:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data/redis
    networks:
      - internal
      - fpm-redis-2

networks:
  internal:
  fpm-redis-1:
  fpm-redis-2:

volumes:
  database_data:
