services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: app/nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./code:/data/mysite.local
      - ./php-socket:/var/run/php
    networks:
      - app-network

  php:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: app/php-fpm
    container_name: php-fpm
    volumes:
      - ./code:/data/mysite.local
      - ./php-socket:/var/run/php
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - '11211:11211'
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
