services:
  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: app_elasticsearch
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 4GB
    environment:
#      HOST: '${HOST}'
#      PORT: '${PORT}'
#      USERNAME: '${USERNAME}'
#      PASSWORD: '${PASSWORD}'
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "true"
