version: '3'

services:
  app-postgres:
    image: postgres:latest
    container_name: otus_1_postgres
    restart: always
    environment:
      POSTGRES_DB: otus-post
      POSTGRES_USER: bool
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
