services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NGINX}
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/data
      - php_socket:/var/run/php
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: docker/fpm
    container_name: ${CONTAINER_APP}
    restart: always
    volumes:
      - php_socket:/var/run/php
      - .:/data
    depends_on:
      - redis
      - elasticsearch
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: ${CONTAINER_REDIS}
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: ${CONTAINER_ELASTICSEARCH}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  php_socket:
  esdata:
    driver: local

networks:
  app_network:
    driver: bridge
