services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app1
      - app2

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
       - .:/data/mysite.local
    networks:
      - app-network
    depends_on:
      - redis

  app1:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app1
    volumes:
      - .:/data/mysite.local
    networks:
      - app-network
    depends_on:
      - redis

  app2:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: balance/php
    container_name: app2
    volumes:
      - .:/data/mysite.local
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
