version: '3.8'

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: otusapp/nginx
    container_name: taskredis_nginx_service
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app_network

  php-fpm:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: otusapp/php # имя будущего образа
    container_name: taskredis_php_fpm_service
    restart: always
    depends_on:
      - redis
      - memcached
    volumes:
      - .:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: taskredis_redis_service
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - app_network

  memcached:
    image: memcached:latest
    container_name: taskredis_memcached_service
    restart: always
    ports:
      - ${MEMCACHED_PORT:-11211}:11211
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
