version: '3.8'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: otusapp/nginx
    container_name: nginx_service
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app_network

  php-fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: otusapp/php # имя будущего образа
    container_name: php_fpm_service
    restart: always
    volumes:
      - ./data:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - redis
      - memcached
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    networks:
      - app_network

  memcached:
    image: memcached:latest
    container_name: memcached_service
    restart: always
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: db_service
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
