services:
  nginx:
    image: "nginx:latest"
    container_name: ${NGINX_CONTAINER}
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: otus-hw22/php-fpm
    container_name: ${APP_CONTAINER}
    restart: always
    volumes:
      - ./app:/var/www/app
    networks:
      - app-network
    env_file: .env

  db:
    image: postgres:latest
    restart: always
    container_name: ${POSTGRES_CONTAINER}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file: .env

networks:
  app-network:
    driver: bridge

volumes:
  db_data: