services:
  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /var/www/html/app
    volumes:
      - ./app:/var/www/html/app
      - ./docker/php-fpm/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./docker/nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8000:80'
    depends_on:
      - php

  db:
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    working_dir: /var/lib/postgresql
    volumes:
      - ./docker/postgres/config/postgresql.conf:/etc/postgres.conf:ro
      - db_pgdata:/var/lib/postgresql/data:rw
      - db_wal:/var/lib/postgresql/wal:rw
    environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    volumes:
      - ./docker/redis/data:/data
    ports:
      - '6379:6379'

  memcached:
    build:
      context: .
      dockerfile: docker/memcached/Dockerfile
    ports:
      - "11211:11211"

volumes:
  db_pgdata:
  db_wal:
