version: '3.8'

services:
  nginx_balancer:
    image: nginx:alpine
    container_name: app_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/upstream/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nginx_instance_1
      - nginx_instance_2
    networks:
      - app-network
  nginx_instance_1:
    build:
      context: ./docker/nginx/instance
    container_name: app_nginx_1
    volumes:
      - ./public:/app/public
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm1
      - php-fpm2
    networks:
      - app-network
  nginx_instance_2:
    build:
      context: ./docker/nginx/instance
    container_name: app_nginx_2
    volumes:
      - ./public:/app/public
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm1
      - php-fpm2
    networks:
      - app-network
  php-fpm1:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app_php_fpm1
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - redis
      - memcached
      - db
  php-fpm2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app_php_fpm2
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - redis
      - memcached
      - db
  redis:
    image: redis:alpine
    container_name: app_redis
    volumes:
      - ./data/redis:/data
    networks:
      - app-network
  memcached:
    image: memcached:alpine
    container_name: app_memcached
    networks:
      - app-network
  db:
    container_name: app_db
    image: postgres:16-alpine3.18
    environment:
      PGDATA: /data/postgres
      PGUSER: ${POSTGRES_ROOT_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/meta/postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d" ]
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge