--
-- PostgreSQL database dump
--

\restrict 7ZyToaTPdPjO7dh6JcQobo2nFSUnbhyoI2XscLbjw2Qm79HWTea8L9FMVa9CYb0

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.0

-- Started on 2026-01-03 10:36:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 239 (class 1259 OID 16695)
-- Name: attribute_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attribute_types (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    data_type character varying(50) NOT NULL,
    category character varying(50) NOT NULL,
    display_format character varying(100),
    CONSTRAINT attribute_types_category_check CHECK (((category)::text = ANY ((ARRAY['review'::character varying, 'award'::character varying, 'important_date'::character varying, 'service_date'::character varying])::text[]))),
    CONSTRAINT attribute_types_data_type_check CHECK (((data_type)::text = ANY ((ARRAY['text'::character varying, 'boolean'::character varying, 'date'::character varying, 'integer'::character varying, 'decimal'::character varying])::text[])))
);


ALTER TABLE public.attribute_types OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16728)
-- Name: attribute_values; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attribute_values (
    id integer NOT NULL,
    movie_id integer NOT NULL,
    attribute_id integer NOT NULL,
    text_value text,
    boolean_value boolean,
    date_value date,
    integer_value integer,
    decimal_value double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.attribute_values OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16709)
-- Name: attributes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attributes (
    id integer NOT NULL,
    type_id integer NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.attributes OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16389)
-- Name: movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    duration_min integer NOT NULL,
    rating character varying(10) NOT NULL,
    genre character varying(100),
    director character varying(255),
    actors text,
    release_date date,
    poster_url character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movies_duration_min_check CHECK ((duration_min > 0))
);


ALTER TABLE public.movies OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16777)
-- Name: actuality_task_today_20days_old; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.actuality_task_today_20days_old AS
 SELECT title AS film_name,
    COALESCE(( SELECT string_agg((a.name)::text, ', '::text ORDER BY (a.name)::text) AS string_agg
           FROM ((public.attribute_values av
             JOIN public.attributes a ON ((av.attribute_id = a.id)))
             JOIN public.attribute_types at ON ((a.type_id = at.id)))
          WHERE ((av.movie_id = m.id) AND ((at.category)::text = 'service_date'::text) AND (av.date_value = CURRENT_DATE))), 'Нет задач'::text) AS actuality_task_today,
    COALESCE(( SELECT string_agg((a.name)::text, ', '::text ORDER BY (a.name)::text) AS string_agg
           FROM ((public.attribute_values av
             JOIN public.attributes a ON ((av.attribute_id = a.id)))
             JOIN public.attribute_types at ON ((a.type_id = at.id)))
          WHERE ((av.movie_id = m.id) AND ((at.category)::text = 'service_date'::text) AND (av.date_value = (CURRENT_DATE + 20)))), 'Нет задач'::text) AS actuality_task_20days_old
   FROM public.movies m
  ORDER BY title;


ALTER VIEW public.actuality_task_today_20days_old OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16694)
-- Name: attribute_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attribute_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attribute_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 16727)
-- Name: attribute_values_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attribute_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attribute_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16708)
-- Name: attributes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attributes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16484)
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(20),
    birth_date date,
    reg_date date DEFAULT CURRENT_DATE NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16483)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16564)
-- Name: discounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.discounts (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    discount_type character varying(20) NOT NULL,
    value numeric(10,2) NOT NULL,
    min_amount numeric(10,2),
    valid_from date NOT NULL,
    valid_to date NOT NULL,
    is_active boolean DEFAULT true,
    conditions text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT discounts_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['percentage'::character varying, 'fixed'::character varying, 'special'::character varying])::text[])))
);


ALTER TABLE public.discounts OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16563)
-- Name: discounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.discounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16407)
-- Name: halls; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.halls (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    total_seats integer NOT NULL,
    schema json NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT halls_total_seats_check CHECK ((total_seats > 0)),
    CONSTRAINT halls_type_check CHECK (((type)::text = ANY ((ARRAY['2D'::character varying, '3D'::character varying, 'IMAX'::character varying, 'VIP'::character varying, '4DX'::character varying])::text[])))
);


ALTER TABLE public.halls OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16406)
-- Name: halls_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.halls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.halls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16809)
-- Name: marketing_view; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.marketing_view AS
 SELECT m.title AS film_name,
    at.name AS type_attribute,
    a.name AS attribute,
        CASE
            WHEN ((at.data_type)::text = 'text'::text) THEN COALESCE(av.text_value, 'Не указано'::text)
            WHEN ((at.data_type)::text = 'boolean'::text) THEN
            CASE
                WHEN (av.boolean_value = true) THEN 'Да'::text
                WHEN (av.boolean_value = false) THEN 'Нет'::text
                ELSE 'Не указано'::text
            END
            WHEN ((at.data_type)::text = 'date'::text) THEN
            CASE
                WHEN (av.date_value IS NOT NULL) THEN to_char((av.date_value)::timestamp with time zone, (COALESCE(at.display_format, 'DD.MM.YYYY'::character varying))::text)
                ELSE 'Не указано'::text
            END
            WHEN ((at.data_type)::text = 'integer'::text) THEN COALESCE((av.integer_value)::text, 'Не указано'::text)
            WHEN ((at.data_type)::text = 'decimal'::text) THEN COALESCE((av.decimal_value)::text, 'Не указано'::text)
            ELSE 'Не указано'::text
        END AS value_data
   FROM (((public.movies m
     JOIN public.attribute_values av ON ((m.id = av.movie_id)))
     JOIN public.attributes a ON ((av.attribute_id = a.id)))
     JOIN public.attribute_types at ON ((a.type_id = at.id)))
  WHERE ((at.category)::text = ANY (ARRAY[('review'::character varying)::text, ('award'::character varying)::text, ('important_date'::character varying)::text]))
  ORDER BY m.title, at.name, a.name;


ALTER VIEW public.marketing_view OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16388)
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16504)
-- Name: price_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.price_rules (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    hall_type character varying(50) NOT NULL,
    seat_type character varying(20) NOT NULL,
    day_of_week integer,
    time_type character varying(20) NOT NULL,
    base_price numeric(10,2) NOT NULL,
    multiplier numeric(3,2) DEFAULT 1.00,
    valid_from date NOT NULL,
    valid_to date,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT price_rules_base_price_check CHECK ((base_price >= (0)::numeric)),
    CONSTRAINT price_rules_day_of_week_check CHECK (((day_of_week >= 1) AND (day_of_week <= 7)))
);


ALTER TABLE public.price_rules OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16503)
-- Name: price_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.price_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16451)
-- Name: screenings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.screenings (
    id integer NOT NULL,
    movie_id integer NOT NULL,
    hall_id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    type character varying(20) DEFAULT 'regular'::character varying NOT NULL,
    language character varying(50) DEFAULT 'original'::character varying,
    subtitles boolean DEFAULT false,
    is_active boolean DEFAULT true,
    CONSTRAINT screenings_check CHECK ((end_time > start_time)),
    CONSTRAINT screenings_type_check CHECK (((type)::text = ANY ((ARRAY['morning'::character varying, 'day'::character varying, 'evening'::character varying, 'night'::character varying, 'premier'::character varying])::text[])))
);


ALTER TABLE public.screenings OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16450)
-- Name: screenings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.screenings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16425)
-- Name: seats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seats (
    id integer NOT NULL,
    hall_id integer NOT NULL,
    row_num integer NOT NULL,
    seat_num integer NOT NULL,
    seat_type character varying(20) DEFAULT 'standard'::character varying NOT NULL,
    zone character varying(50) DEFAULT 'main'::character varying,
    is_active boolean DEFAULT true,
    CONSTRAINT seats_row_num_check CHECK ((row_num > 0)),
    CONSTRAINT seats_seat_num_check CHECK ((seat_num > 0)),
    CONSTRAINT seats_seat_type_check CHECK (((seat_type)::text = ANY ((ARRAY['standard'::character varying, 'vip'::character varying, 'sofa'::character varying, 'handicap'::character varying])::text[])))
);


ALTER TABLE public.seats OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16424)
-- Name: seats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16581)
-- Name: ticket_discounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_discounts (
    ticket_id integer NOT NULL,
    discount_id integer NOT NULL,
    applied_amount numeric(10,2) NOT NULL
);


ALTER TABLE public.ticket_discounts OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16526)
-- Name: tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tickets (
    id integer NOT NULL,
    screening_id integer NOT NULL,
    seat_id integer NOT NULL,
    customer_id integer,
    price numeric(10,2) NOT NULL,
    status character varying(20) DEFAULT 'sold'::character varying NOT NULL,
    purchase_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    payment_method character varying(50) DEFAULT 'cash'::character varying,
    reservation_expires timestamp without time zone,
    CONSTRAINT tickets_price_check CHECK ((price >= (0)::numeric)),
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['sold'::character varying, 'reserved'::character varying, 'cancelled'::character varying, 'refunded'::character varying])::text[])))
);


ALTER TABLE public.tickets OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16525)
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5106 (class 0 OID 16695)
-- Dependencies: 239
-- Data for Name: attribute_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attribute_types (id, name, data_type, category, display_format) FROM stdin;
1	Рецензии	text	review	\N
2	Премии	boolean	award	\N
3	Важные даты	date	important_date	DD.MM.YYYY
4	Служебные даты	date	service_date	YYYY-MM-DD
\.


--
-- TOC entry 5110 (class 0 OID 16728)
-- Dependencies: 243
-- Data for Name: attribute_values; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attribute_values (id, movie_id, attribute_id, text_value, boolean_value, date_value, integer_value, decimal_value, created_at) FROM stdin;
19	1	9	«Интерстеллар» — это визуально ошеломляющая и эмоционально мощная ода человеческому духу и силе любви, преодолевающей пространство и время.	\N	\N	\N	\N	2025-12-24 10:14:19.60568
20	2	9	Искренняя и трогательная история о дружбе, которая преодолевает расовые предрассудки. Отличная игра актеров и тонкий юмор.	\N	\N	\N	\N	2025-12-24 10:14:19.60568
21	3	9	Возвращение Гая Ричи к корням: умный, стильный и полный черного юмора криминальный боевик.	\N	\N	\N	\N	2025-12-24 10:14:19.60568
22	1	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
23	2	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
24	4	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
25	5	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
26	6	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
27	7	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
28	10	11	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
29	2	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
30	4	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
31	5	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
32	7	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
33	8	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
34	9	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
35	10	12	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
36	3	13	\N	t	\N	\N	\N	2025-12-24 10:14:19.60568
37	1	14	\N	\N	2014-10-26	\N	\N	2025-12-24 10:14:19.60568
38	10	14	\N	\N	1997-11-01	\N	\N	2025-12-24 10:14:19.60568
39	2	15	\N	\N	2019-02-07	\N	\N	2025-12-24 10:14:19.60568
40	4	16	\N	\N	2019-05-21	\N	\N	2025-12-24 10:14:19.60568
44	1	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
45	1	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
46	2	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
47	2	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
49	3	17	\N	\N	2026-01-13	\N	\N	2025-12-24 10:25:12.210109
50	3	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
51	3	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
52	4	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
53	4	18	\N	\N	2026-01-13	\N	\N	2025-12-24 10:25:12.210109
54	4	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
55	5	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
56	5	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
57	5	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
58	6	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
59	6	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
60	6	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
61	7	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
62	7	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
63	7	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
64	8	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
65	8	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
66	8	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
67	9	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
68	9	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
69	9	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
70	10	17	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
71	10	18	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
72	10	19	\N	\N	\N	\N	\N	2025-12-24 10:25:12.210109
41	1	17	\N	\N	2025-12-31	\N	\N	2025-12-24 10:14:19.60568
42	2	19	\N	\N	2025-12-31	\N	\N	2025-12-24 10:14:19.60568
\.


--
-- TOC entry 5108 (class 0 OID 16709)
-- Dependencies: 241
-- Data for Name: attributes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attributes (id, type_id, code, name) FROM stdin;
9	1	critics_review	Рецензия критиков
10	1	academy_review	Отзыв киноакадемии
11	2	oscar	Оскар
12	2	golden_globe	Золотой глобус
13	2	bafta	Премия BAFTA
14	3	world_premier	Мировая премьера
15	3	russia_premier	Премьера в РФ
16	3	festival	Показ на фестивале
17	4	tickets_start	Начало продажи билетов
18	4	tv_ad_start	Запуск рекламы на ТВ
19	4	promo_start	Начало промо-кампании
\.


--
-- TOC entry 5097 (class 0 OID 16484)
-- Dependencies: 230
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, name, email, phone, birth_date, reg_date, is_active, created_at) FROM stdin;
\.


--
-- TOC entry 5103 (class 0 OID 16564)
-- Dependencies: 236
-- Data for Name: discounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.discounts (id, name, discount_type, value, min_amount, valid_from, valid_to, is_active, conditions, created_at) FROM stdin;
\.


--
-- TOC entry 5091 (class 0 OID 16407)
-- Dependencies: 224
-- Data for Name: halls; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.halls (id, name, type, total_seats, schema, created_at) FROM stdin;
\.


--
-- TOC entry 5089 (class 0 OID 16389)
-- Dependencies: 222
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movies (id, title, description, duration_min, rating, genre, director, actors, release_date, poster_url, created_at, updated_at) FROM stdin;
1	Интерстеллар	Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека и найти планету с подходящими для человечества условиями.	169	PG-13	Фантастика, драма, приключения	Кристофер Нолан	Мэттью Макконахи, Энн Хэтэуэй, Джессика Честейн, Майкл Кейн	2014-10-26	https://example.com/posters/interstellar.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
2	Зеленая книга	Утончённый светский аристократ нанимает в качестве водителя и телохранителя грубоватого вышибалу из ночного клуба. Вместе они отправляются в турне по южным штатам Америки 1960-х, где расовые предрассудки всё ещё являются нормой.	130	PG-13	Биография, драма, комедия	Питер Фаррелли	Вигго Мортенсен, Махершала Али, Линда Карделлини, Себастьян Манискалко	2018-11-16	https://example.com/posters/greenbook.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
3	Джентльмены	Талантливый выпускник Оксфорда, применив свой уникальный ум и невиданную дерзость, придумал нелегальную схему обогащения. Он выращивал и продавал марихуану, используя поместья обедневшей английской аристократии.	113	R	Криминал, боевик, комедия	Гай Ричи	Мэттью Макконахи, Чарли Ханнэм, Хью Грант, Мишель Докери	2019-12-03	https://example.com/posters/gentlemen.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
4	Паразиты	Обычное корейское семейство Кимов жизнь не балует. Приходится жить в сыром полуподвале, воровать интернет у соседей и перебиваться случайными подработками. Однажды друг сына семейства, уезжая на стажировку за границу, предлагает тому заменить его и поработать репетитором у старшеклассницы в богатой семье Пак. Подделав диплом о высшем образовании, парень отправляется в шикарный район Сеула и производит на хозяйку дома хорошее впечатление. Тут же ему в голову приходит необычный план по трудоустройству сестры.	132	R	Драма, комедия, триллер	Пон Джун Хо	Сон Кан Хо, Ли Сон Гюн, Чо Ё Чон, Чхве У Сик	2019-05-21	https://example.com/posters/parasite.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
5	1917	6 апреля 1917 года, разгар Первой мировой войны. Во время отступления германской армии с западного фронта британский генерал получает секретную информацию о том, что враг заманивает союзников в ловушку. Чтобы спасти от неминуемой гибели 1600 солдат, среди которых находится и брат одного из них, два капрала должны пересечь вражескую территорию и доставить приказ об отмене наступления.	119	R	Драма, военный	Сэм Мендес	Джордж Маккей, Дин-Чарльз Чепмен, Марк Стронг, Эндрю Скотт	2019-12-04	https://example.com/posters/1917.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
6	Дюна	Наследник знаменитого дома Атрейдесов Пол отправляется вместе с семьей на одну из самых опасных планет во Вселенной — Арракис. Здесь нет ничего, кроме песка, палящего солнца, гигантских чудовищ и основной причины межгалактических конфликтов — невероятно ценного ресурса, который называется меланж. В результате захвата власти Пол вынужден бежать и скрываться, и это становится началом его пути к загадочной Дюне и исполнению своего древнего предназначения.	155	PG-13	Фантастика, приключения, драма	Дени Вильнёв	Тимоти Шаламе, Ребекка Фергюсон, Зендея, Оскар Айзек	2021-09-03	https://example.com/posters/dune.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
7	Оппенгеймер	История жизни американского физика-теоретика Роберта Оппенгеймера, который во время Второй мировой войны руководил Манхэттенским проектом — программой по разработке ядерного оружия.	180	R	Биография, драма, история	Кристофер Нолан	Киллиан Мерфи, Эмили Блант, Мэтт Деймон, Роберт Дауни мл.	2023-07-11	https://example.com/posters/oppenheimer.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
8	Барби	Кукла Барби живёт в сказочной стране Барбиленде, где каждый день идеален. Но однажды она обнаруживает, что с ней происходит нечто странное, и отправляется в реальный мир, чтобы выяснить причину. Кен отправляется вместе с ней, поскольку не мыслит своей жизни без Барби.	114	PG-13	Комедия, фэнтези, приключения	Грета Гервиг	Марго Робби, Райан Гослинг, Америка Феррера, Кейт Маккиннон	2023-07-09	https://example.com/posters/barbie.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
9	Аватар: Путь воды	Джейк Салли вместе со своей семьей продолжает привыкать к жизни в племени Нави. Однако теперь им предстоит покинуть родные края и отправиться исследовать другие территории Пандоры. Но их путешествие омрачает возвращение хорошо знакомой угрозы из мира людей.	192	PG-13	Фантастика, приключения, боевик	Джеймс Кэмерон	Сэм Уортингтон, Зои Салдана, Сигурни Уивер, Стивен Лэнг	2022-12-06	https://example.com/posters/avatar2.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
10	Титаник	В первом и последнем плавании шикарного «Титаника» встречаются двое. Пассажир нижней палубы Джек выиграл билет в карты, а богатая наследница Роза отправляется в Америку, чтобы выйти замуж по расчёту. Чувства молодых людей только успевают расцвести, и даже не классовые различия создадут испытания влюблённым, а айсберг, вставший на пути считавшегося непотопляемым лайнера.	194	PG-13	Драма, мелодрама	Джеймс Кэмерон	Леонардо ДиКаприо, Кейт Уинслет, Билли Зейн, Кэти Бейтс	1997-11-01	https://example.com/posters/titanic.jpg	2025-12-24 10:08:44.855083	2025-12-24 10:08:44.855083
\.


--
-- TOC entry 5099 (class 0 OID 16504)
-- Dependencies: 232
-- Data for Name: price_rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.price_rules (id, name, hall_type, seat_type, day_of_week, time_type, base_price, multiplier, valid_from, valid_to, is_active, created_at) FROM stdin;
\.


--
-- TOC entry 5095 (class 0 OID 16451)
-- Dependencies: 228
-- Data for Name: screenings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.screenings (id, movie_id, hall_id, start_time, end_time, type, language, subtitles, is_active) FROM stdin;
\.


--
-- TOC entry 5093 (class 0 OID 16425)
-- Dependencies: 226
-- Data for Name: seats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seats (id, hall_id, row_num, seat_num, seat_type, zone, is_active) FROM stdin;
\.


--
-- TOC entry 5104 (class 0 OID 16581)
-- Dependencies: 237
-- Data for Name: ticket_discounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_discounts (ticket_id, discount_id, applied_amount) FROM stdin;
\.


--
-- TOC entry 5101 (class 0 OID 16526)
-- Dependencies: 234
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tickets (id, screening_id, seat_id, customer_id, price, status, purchase_time, payment_method, reservation_expires) FROM stdin;
\.


--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 238
-- Name: attribute_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attribute_types_id_seq', 4, true);


--
-- TOC entry 5117 (class 0 OID 0)
-- Dependencies: 242
-- Name: attribute_values_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attribute_values_id_seq', 72, true);


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 240
-- Name: attributes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attributes_id_seq', 19, true);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 229
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 1, false);


--
-- TOC entry 5120 (class 0 OID 0)
-- Dependencies: 235
-- Name: discounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.discounts_id_seq', 1, false);


--
-- TOC entry 5121 (class 0 OID 0)
-- Dependencies: 223
-- Name: halls_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.halls_id_seq', 1, false);


--
-- TOC entry 5122 (class 0 OID 0)
-- Dependencies: 221
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movies_id_seq', 10, true);


--
-- TOC entry 5123 (class 0 OID 0)
-- Dependencies: 231
-- Name: price_rules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.price_rules_id_seq', 1, false);


--
-- TOC entry 5124 (class 0 OID 0)
-- Dependencies: 227
-- Name: screenings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.screenings_id_seq', 1, false);


--
-- TOC entry 5125 (class 0 OID 0)
-- Dependencies: 225
-- Name: seats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seats_id_seq', 1, false);


--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 233
-- Name: tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tickets_id_seq', 1, false);


--
-- TOC entry 4906 (class 2606 OID 16707)
-- Name: attribute_types attribute_types_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_types
    ADD CONSTRAINT attribute_types_name_key UNIQUE (name);


--
-- TOC entry 4908 (class 2606 OID 16705)
-- Name: attribute_types attribute_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_types
    ADD CONSTRAINT attribute_types_pkey PRIMARY KEY (id);


--
-- TOC entry 4925 (class 2606 OID 16740)
-- Name: attribute_values attribute_values_movie_attribute_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_values
    ADD CONSTRAINT attribute_values_movie_attribute_key UNIQUE (movie_id, attribute_id);


--
-- TOC entry 4927 (class 2606 OID 16738)
-- Name: attribute_values attribute_values_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_values
    ADD CONSTRAINT attribute_values_pkey PRIMARY KEY (id);


--
-- TOC entry 4914 (class 2606 OID 16719)
-- Name: attributes attributes_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attributes
    ADD CONSTRAINT attributes_code_key UNIQUE (code);


--
-- TOC entry 4916 (class 2606 OID 16721)
-- Name: attributes attributes_name_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attributes
    ADD CONSTRAINT attributes_name_type_key UNIQUE (type_id, name);


--
-- TOC entry 4918 (class 2606 OID 16717)
-- Name: attributes attributes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attributes
    ADD CONSTRAINT attributes_pkey PRIMARY KEY (id);


--
-- TOC entry 4879 (class 2606 OID 16498)
-- Name: customers customers_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_email_key UNIQUE (email);


--
-- TOC entry 4881 (class 2606 OID 16500)
-- Name: customers customers_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_phone_key UNIQUE (phone);


--
-- TOC entry 4883 (class 2606 OID 16496)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 16579)
-- Name: discounts discounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 16423)
-- Name: halls halls_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.halls
    ADD CONSTRAINT halls_name_key UNIQUE (name);


--
-- TOC entry 4864 (class 2606 OID 16421)
-- Name: halls halls_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.halls
    ADD CONSTRAINT halls_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 16402)
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 16522)
-- Name: price_rules price_rules_hall_type_seat_type_day_of_week_time_type_valid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price_rules
    ADD CONSTRAINT price_rules_hall_type_seat_type_day_of_week_time_type_valid_key UNIQUE (hall_type, seat_type, day_of_week, time_type, valid_from);


--
-- TOC entry 4891 (class 2606 OID 16520)
-- Name: price_rules price_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price_rules
    ADD CONSTRAINT price_rules_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 16469)
-- Name: screenings screenings_hall_id_start_time_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_hall_id_start_time_key UNIQUE (hall_id, start_time);


--
-- TOC entry 4877 (class 2606 OID 16467)
-- Name: screenings screenings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 16442)
-- Name: seats seats_hall_id_row_num_seat_num_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_hall_id_row_num_seat_num_key UNIQUE (hall_id, row_num, seat_num);


--
-- TOC entry 4870 (class 2606 OID 16440)
-- Name: seats seats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 16588)
-- Name: ticket_discounts ticket_discounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_discounts
    ADD CONSTRAINT ticket_discounts_pkey PRIMARY KEY (ticket_id, discount_id);


--
-- TOC entry 4897 (class 2606 OID 16541)
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 16543)
-- Name: tickets tickets_screening_id_seat_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_screening_id_seat_id_key UNIQUE (screening_id, seat_id);


--
-- TOC entry 4909 (class 1259 OID 16788)
-- Name: idx_attribute_types_category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attribute_types_category ON public.attribute_types USING btree (category);


--
-- TOC entry 4910 (class 1259 OID 16790)
-- Name: idx_attribute_types_category_data_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attribute_types_category_data_type ON public.attribute_types USING btree (category, data_type);


--
-- TOC entry 4911 (class 1259 OID 16789)
-- Name: idx_attribute_types_data_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attribute_types_data_type ON public.attribute_types USING btree (data_type);


--
-- TOC entry 4912 (class 1259 OID 16787)
-- Name: idx_attribute_types_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attribute_types_name ON public.attribute_types USING btree (name);


--
-- TOC entry 4919 (class 1259 OID 16791)
-- Name: idx_attributes_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attributes_code ON public.attributes USING btree (code);


--
-- TOC entry 4920 (class 1259 OID 16795)
-- Name: idx_attributes_covering; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attributes_covering ON public.attributes USING btree (type_id, code, name);


--
-- TOC entry 4921 (class 1259 OID 16792)
-- Name: idx_attributes_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attributes_name ON public.attributes USING btree (name);


--
-- TOC entry 4922 (class 1259 OID 16794)
-- Name: idx_attributes_popular_codes; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attributes_popular_codes ON public.attributes USING btree (code) WHERE ((code)::text = ANY ((ARRAY['oscar'::character varying, 'golden_globe'::character varying, 'bafta'::character varying, 'critics_review'::character varying, 'world_premier'::character varying])::text[]));


--
-- TOC entry 4923 (class 1259 OID 16793)
-- Name: idx_attributes_type_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attributes_type_id ON public.attributes USING btree (type_id);


--
-- TOC entry 4892 (class 1259 OID 16559)
-- Name: idx_customer_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_customer_id ON public.tickets USING btree (customer_id);


--
-- TOC entry 4884 (class 1259 OID 16501)
-- Name: idx_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_email ON public.customers USING btree (email);


--
-- TOC entry 4856 (class 1259 OID 16404)
-- Name: idx_genre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_genre ON public.movies USING btree (genre);


--
-- TOC entry 4865 (class 1259 OID 16448)
-- Name: idx_hall_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_hall_id ON public.seats USING btree (hall_id);


--
-- TOC entry 4886 (class 1259 OID 16523)
-- Name: idx_hall_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_hall_type ON public.price_rules USING btree (hall_type);


--
-- TOC entry 4871 (class 1259 OID 16480)
-- Name: idx_movie_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_movie_id ON public.screenings USING btree (movie_id);


--
-- TOC entry 4885 (class 1259 OID 16502)
-- Name: idx_phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_phone ON public.customers USING btree (phone);


--
-- TOC entry 4893 (class 1259 OID 16561)
-- Name: idx_purchase_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_purchase_time ON public.tickets USING btree (purchase_time);


--
-- TOC entry 4857 (class 1259 OID 16405)
-- Name: idx_release_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_release_date ON public.movies USING btree (release_date);


--
-- TOC entry 4894 (class 1259 OID 16562)
-- Name: idx_screening_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_screening_id ON public.tickets USING btree (screening_id);


--
-- TOC entry 4866 (class 1259 OID 16449)
-- Name: idx_seat_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_seat_type ON public.seats USING btree (seat_type);


--
-- TOC entry 4872 (class 1259 OID 16481)
-- Name: idx_start_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_start_time ON public.screenings USING btree (start_time);


--
-- TOC entry 4895 (class 1259 OID 16560)
-- Name: idx_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_status ON public.tickets USING btree (status);


--
-- TOC entry 4887 (class 1259 OID 16524)
-- Name: idx_time_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_time_type ON public.price_rules USING btree (time_type);


--
-- TOC entry 4858 (class 1259 OID 16403)
-- Name: idx_title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_title ON public.movies USING btree (title);


--
-- TOC entry 4873 (class 1259 OID 16482)
-- Name: idx_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_type ON public.screenings USING btree (type);


--
-- TOC entry 4902 (class 1259 OID 16580)
-- Name: idx_validity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_validity ON public.discounts USING btree (valid_from, valid_to);


--
-- TOC entry 4937 (class 2606 OID 16746)
-- Name: attribute_values attribute_values_attribute_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_values
    ADD CONSTRAINT attribute_values_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.attributes(id) ON DELETE CASCADE;


--
-- TOC entry 4938 (class 2606 OID 16741)
-- Name: attribute_values attribute_values_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_values
    ADD CONSTRAINT attribute_values_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(id) ON DELETE CASCADE;


--
-- TOC entry 4936 (class 2606 OID 16722)
-- Name: attributes attributes_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attributes
    ADD CONSTRAINT attributes_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.attribute_types(id) ON DELETE CASCADE;


--
-- TOC entry 4929 (class 2606 OID 16475)
-- Name: screenings screenings_hall_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_hall_id_fkey FOREIGN KEY (hall_id) REFERENCES public.halls(id) ON DELETE CASCADE;


--
-- TOC entry 4930 (class 2606 OID 16470)
-- Name: screenings screenings_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(id) ON DELETE CASCADE;


--
-- TOC entry 4928 (class 2606 OID 16443)
-- Name: seats seats_hall_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_hall_id_fkey FOREIGN KEY (hall_id) REFERENCES public.halls(id) ON DELETE CASCADE;


--
-- TOC entry 4934 (class 2606 OID 16594)
-- Name: ticket_discounts ticket_discounts_discount_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_discounts
    ADD CONSTRAINT ticket_discounts_discount_id_fkey FOREIGN KEY (discount_id) REFERENCES public.discounts(id) ON DELETE CASCADE;


--
-- TOC entry 4935 (class 2606 OID 16589)
-- Name: ticket_discounts ticket_discounts_ticket_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_discounts
    ADD CONSTRAINT ticket_discounts_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE;


--
-- TOC entry 4931 (class 2606 OID 16554)
-- Name: tickets tickets_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;


--
-- TOC entry 4932 (class 2606 OID 16544)
-- Name: tickets tickets_screening_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_screening_id_fkey FOREIGN KEY (screening_id) REFERENCES public.screenings(id) ON DELETE CASCADE;


--
-- TOC entry 4933 (class 2606 OID 16549)
-- Name: tickets tickets_seat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES public.seats(id) ON DELETE CASCADE;


-- Completed on 2026-01-03 10:36:24

--
-- PostgreSQL database dump complete
--

\unrestrict 7ZyToaTPdPjO7dh6JcQobo2nFSUnbhyoI2XscLbjw2Qm79HWTea8L9FMVa9CYb0

