openapi: 3.0.0
info:
  title: Queue API
  description: API для асинхронной обработки запросов через очереди
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Development server
paths:
  /jobs:
    post:
      summary: Создать новую задачу
      description: Принимает данные для обработки и возвращает ID задачи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object
                  description: Данные для обработки
                  example: {"items": ["test1", "test2"]}
      responses:
        '201':
          description: Задача создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    example: "job_65a8f1b2c3d4e"
                  status:
                    type: string
                    example: "pending"
        '400':
          description: Неверные входные данные
  /jobs/{job_id}:
    get:
      summary: Получить статус задачи
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Информация о задаче
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                  status:
                    type: string
                    enum: [pending, processing, completed, failed]
                  result:
                    type: object
                    nullable: true
        '404':
          description: Задача не найдена