user nginx;
worker_processes auto;
pid /var/run/nginx/nginx.pid;  # ← Здесь на глобальном уровне

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
}