server {
    listen 80;
    server_name localhost;
    root /app/src/public;
    index index.php index.html;


    location ~ /\.(ht|git|env) {
        deny all;
        return 404;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|html|woff2?|ttf|svg)$ {
        access_log off;
        expires max;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

    }
}
