controllers:
  resource:
#    path: ../../src/Controller/
    path: ../../src/Infrastructure/Controller/
#    namespace: App\Controller
    namespace: App\Infrastructure\Controller
  type: attribute

kernel:
  resource: App\Kernel
  type: attribute
