version: '3'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: hw5/app
    container_name: hw5-app
    volumes:
      - ./app:/var/www/html/app
      - ./docker/php/php-socket:/var/run/php
    networks:
      - otus-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: hw5/nginx
    container_name: hw5-nginx
    volumes:
      - ./app:/var/www/html/app
      - ./docker/php/php-socket:/var/run/php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - otus-network


networks:
  otus-network:
    driver: bridge
