<?php

declare(strict_types=1);

namespace App\Controller\Cli\Command;

use App\Core\Database\Connection\PDOWrapper;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand('db:table:create:users')]
class CreateUsersTableCommand extends Command
{
    public function __construct(
        private readonly PDOWrapper $pdoWrapper,
    ) {
        parent::__construct();
    }

    public function __invoke(OutputInterface $output): int
    {
        $columnDefinitionList = [
            'id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY',
            'first_name VARCHAR(50) NOT NULL',
            'last_name VARCHAR(50) NOT NULL',
            'email VARCHAR(255) NOT NULL',
            'birth_date DATE NOT NULL',
            'status BOOLEAN NOT NULL DEFAULT TRUE',
        ];

        $sql = sprintf('CREATE TABLE IF NOT EXISTS users (%s)', implode(', ', $columnDefinitionList));
        $this->pdoWrapper->getHandler()->prepare($sql)->execute();

        $output->writeln('Таблица пользователей создана.');

        return Command::SUCCESS;
    }
}
