controllers:
    resource:
        path: ../src/Infrastructure/Http
        namespace: App\Infrastructure\Http
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: {_controller: nelmio_api_doc.controller.swagger_ui}
