# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  report_upload: 'Resource/Report'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    bind:
      # при создании экземпляра App\Shared\Infrastructure\Service\FileHelper с именем переменной $reportFileHelper создается тот или иной сервис (описан ниже)
      App\Shared\Application\Service\FileHelperInterface $reportFileHelper: '@file_helper.report'
      League\Flysystem\Filesystem $reportFileSystem: '@oneup_flysystem.upload_reports_filesystem'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'

  ##filehandler
  file_helper.report:
    class: App\Shared\Infrastructure\Service\FileHelper
    arguments:
      $reportFileSystem: '@oneup_flysystem.upload_reports_filesystem'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
