POST http://localhost:{{nginxPublishedPort}}//brackets/balance-check
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
    "string": "(()()()()))((((()()()))(()()()(((()))))))"
}
