apiVersion: v1
kind: Secret
metadata:
    name: application
type: Opaque
stringData:
    DATABASE_DSN: "pgsql:host=postgres;port=5432;dbname=otus"
    DATABASE_USERNAME: "otus"
    DATABASE_PASSWORD: "otus"
    QUEUE_REALTIME_HOST: "rabbitmq"
    QUEUE_REALTIME_PORT: "5672"
    QUEUE_REALTIME_USER: "otus"
    QUEUE_REALTIME_PASSWORD: "otus"
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: "otus"
---
apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
type: Opaque
stringData:
    RABBITMQ_DEFAULT_USER: "otus"
    RABBITMQ_DEFAULT_PASS: "otus"
