<?php

namespace App\Controller\Command;

use App\Infrastructure\Database\Connection\PDOWrapper;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand('db:users:create')]
class CreateUsersTableCommand extends Command
{
    public function __invoke(OutputInterface $output): int
    {
        $columnDefinitionList = [
            'id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY',
            'first_name VARCHAR(50) NOT NULL',
            'last_name VARCHAR(50) NOT NULL',
            'email VARCHAR(255) NOT NULL',
            'birth_date DATE NOT NULL',
            'status BOOLEAN NOT NULL DEFAULT TRUE',
        ];

        $sql = sprintf('CREATE TABLE users (%s)', implode(', ', $columnDefinitionList));
        PDOWrapper::getHandler()->prepare($sql)->execute();

        $output->writeln('Таблица пользователей успешно создана.');

        return Command::SUCCESS;
    }
}
