services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www/html:ro
      - php-socket:/var/run/php
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
      - php-socket:/var/run/php
    depends_on:
      - redis
      - memcached
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./docker/data/redis:/data

  memcached:
    image: memcached:alpine
    container_name: memcached

  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data

volumes:
  php-socket:

networks:
  default:
    driver: bridge
