FROM php:8.2-cli

RUN apt-get update && apt-get install -y libsqlite3-dev unzip \
    && docker-php-ext-install pdo_sqlite

RUN pecl install redis && docker-php-ext-enable redis

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock* ./

RUN composer install

COPY . .

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080", "-t", "public"]

