services:
  nginx:
    container_name: Nginx-Balancer
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: balancer-nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www/app
      - ../public:/var/www/public
      - ../vendor:/var/www/vendor:ro
      - ../docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../docker/nginx/conf/upstreams.conf:/etc/nginx/conf.d/upstreams.conf:ro
      - ../docker/_logs/nginx:/var/log/nginx
    depends_on:
      - php1
      - php2
      - php3
    networks:
      otus_hw:
        ipv4_address: 172.30.0.1

  php1:
    container_name: PhpFpm_S1
    build:
      context: ./php
      dockerfile: Dockerfile
    image: balancer-php:fpm-alpine
    volumes:
      - ../app:/var/www/app
      - ../public:/var/www/public
      - ../vendor:/var/www/vendor:ro
      - ../docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ../docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ../docker/php/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ../docker/_logs/php:/var/log/php
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      otus_hw:
        ipv4_address: 172.30.0.10

  php2:
    container_name: PhpFpm_S2
    build:
      context: ./php
      dockerfile: Dockerfile
    image: balancer-php:fpm-alpine
    volumes:
      - ../app:/var/www/app
      - ../public:/var/www/public
      - ../vendor:/var/www/vendor:ro
      - ../docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ../docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ../docker/php/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ../docker/_logs/php:/var/log/php
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      otus_hw:
        ipv4_address: 172.30.0.11

  php3:
    container_name: PhpFpm_S3
    build:
      context: ./php
      dockerfile: Dockerfile
    image: balancer-php:fpm-alpine
    volumes:
      - ../app:/var/www/app
      - ../public:/var/www/public
      - ../vendor:/var/www/vendor:ro
      - ../docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ../docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ../docker/php/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ../docker/_logs/php:/var/log/php
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      otus_hw:
        ipv4_address: 172.30.0.12

  redis1:
    container_name: Redis_S1
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: balancer-redis:7.4-alpine
    volumes:
      - ../docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ../docker/_data/redis_s1:/data
      - ../docker/_logs/redis_s1:/var/log/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      otus_hw:
        ipv4_address: 172.30.0.20

  redis2:
    container_name: Redis_S2
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: balancer-redis:7.4-alpine
    volumes:
      - ../docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ../docker/_data/redis_s2:/data
      - ../docker/_logs/redis_s2:/var/log/redis
    depends_on:
      - redis1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      otus_hw:
        ipv4_address: 172.30.0.21

  redis3:
    container_name: Redis_S3
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: balancer-redis:7.4-alpine
    volumes:
      - ../docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ../docker/_data/redis_s3:/data
      - ../docker/_logs/redis_s3:/var/log/redis
    depends_on:
      - redis1
      - redis2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      otus_hw:
        ipv4_address: 172.30.0.22

# Настроим общую сеть для контейнеров
networks:
  otus_hw:
    name: "otus_balancer_nginx"
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.30.5.0/24
          gateway: 172.30.5.254
