version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx2025
    container_name: ${CONTAINER_NAME_NGINX}
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network


  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php2025
    container_name: ${CONTAINER_NAME_PHP}
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network


networks:
  app-network:
    driver: bridge