services:
  app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    volumes:
      - ..:/app
      - data:/data
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ../swagger/openapi.yaml:/docs/openapi.yaml

volumes:
  redis-data:
  data: