upstream nginx_backend {
    server nginx_1:80 max_fails=3 fail_timeout=5s;
    server nginx_2:80 max_fails=3 fail_timeout=5s;
}

server {
    listen 80 default_server;
    server_name _;

    location / {
        proxy_pass http://nginx_backend;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
    }
}