#!/bin/bash
set -euo pipefail

SLOT="${1:?Usage: deploy-slot.sh blue|green}"

if [ "$SLOT" != "blue" ] && [ "$SLOT" != "green" ]; then
    echo "--- ERROR: Slot must be 'blue' or 'green', got '$SLOT'"
    exit 1
fi

DEPLOY_DIR="${DEPLOY_DIR:-/opt/mkd-bot}"
COMPOSE_APP_SRC="$DEPLOY_DIR/docker-compose.app.yml"
COMPOSE_INFRA="$DEPLOY_DIR/docker-compose.infra.yml"
ENV_FILE="$(readlink -f "$DEPLOY_DIR/.env" 2>/dev/null || echo "$DEPLOY_DIR/.env")"
PROJECT_NAME="mkd-bot-${SLOT}"

if [ ! -f "$ENV_FILE" ]; then
    echo "--- ERROR: .env file not found at $ENV_FILE"
    echo "In CI/CD: .env is auto-generated by render-env.sh (check deploy:slot before_script)."
    echo "Manual run: bash deploy/scripts/render-env.sh deploy/env.template $ENV_FILE"
    exit 1
fi

cd "$DEPLOY_DIR"

# External-сеть для изоляции слотов; создаём, если не существует
docker network create mkd-bot-network 2>/dev/null || true

# Подставляем переменные шаблона в compose-файл
render_compose() {
    local slot="$1"
    export SLOT="$slot"
    export SLOT_ROLE="${SLOT_ROLE:-passive}"
    export CI_REGISTRY_IMAGE="${CI_REGISTRY_IMAGE:-mkd-bot}"
    export APP_VERSION="${APP_VERSION:-latest}"
    local rendered="$DEPLOY_DIR/docker-compose.app.${slot}.yml"
    envsubst '$SLOT $SLOT_ROLE $CI_REGISTRY_IMAGE $APP_VERSION $DEPLOY_DIR' < "$COMPOSE_APP_SRC" > "$rendered"
}

COMPOSE_APP_RENDERED="$DEPLOY_DIR/docker-compose.app.${SLOT}.yml"

echo "=== [1/3] Pulling images from Registry ==="
render_compose "$SLOT"
docker compose --env-file "$ENV_FILE" -p "$PROJECT_NAME" -f "$COMPOSE_APP_RENDERED" pull app

echo "=== [2/3] Starting containers in PASSIVE mode ==="
export SLOT_ROLE=passive
render_compose "$SLOT"
docker compose --env-file "$ENV_FILE" -p "$PROJECT_NAME" -f "$COMPOSE_APP_RENDERED" up -d --force-recreate app webserver

echo "=== [3/3] Waiting for containers to start ==="
sleep 5

echo "=== Deploy to $SLOT slot complete (PASSIVE mode) ==="
echo "Next steps:"
echo " 1. Run migrations: docker exec ${SLOT}-app php /data/bin/migrate.php"
echo " 2. Health check: bash deploy/scripts/health-check.sh $SLOT"
echo " 3. Switch traffic: bash deploy/scripts/switch-slot.sh $SLOT"
