#!/bin/bash
set -euo pipefail

NEW_SLOT="${1:?Usage: switch-slot.sh blue|green}"

if [ "$NEW_SLOT" != "blue" ] && [ "$NEW_SLOT" != "green" ]; then
    echo "--- ERROR: Slot must be 'blue' or 'green', got '$NEW_SLOT'"
    exit 1
fi

DEPLOY_DIR="${DEPLOY_DIR:-/opt/mkd-bot}"
STATE_FILE="$DEPLOY_DIR/.active-slot"
LOCK_FILE="$DEPLOY_DIR/.switch-lock"
ENV_FILE="$DEPLOY_DIR/.env"
COMPOSE_APP_SRC="$DEPLOY_DIR/docker-compose.app.yml"
COMPOSE_INFRA="$DEPLOY_DIR/docker-compose.infra.yml"

if [ ! -f "$ENV_FILE" ]; then
    echo "--- ERROR: .env file not found at $ENV_FILE"
    echo "In CI/CD: .env is auto-generated by render-env.sh (check switch:traffic before_script)."
    echo "Manual run: bash deploy/scripts/render-env.sh deploy/env.template $ENV_FILE"
    exit 1
fi

cd "$DEPLOY_DIR"

# Подставляем переменные шаблона в compose-файл
render_compose() {
    local slot="$1"
    export SLOT="$slot"
    export SLOT_ROLE="${SLOT_ROLE:-passive}"
    export CI_REGISTRY_IMAGE="${CI_REGISTRY_IMAGE:-mkd-bot}"
    export APP_VERSION="${APP_VERSION:-latest}"
    local rendered="$DEPLOY_DIR/docker-compose.app.${slot}.yml"
    envsubst '$SLOT $SLOT_ROLE $CI_REGISTRY_IMAGE $APP_VERSION $DEPLOY_DIR' < "$COMPOSE_APP_SRC" > "$rendered"
}

get_project_name() {
    local slot="$1"
    echo "mkd-bot-${slot}"
}

# File-lock: защищаем от параллельного запуска switch
exec 200>"$LOCK_FILE"
if ! flock -n 200; then
    echo "--- ERROR: Another switch operation is already running (lock: $LOCK_FILE)"
    exit 1
fi
trap "rm -f $LOCK_FILE" EXIT

OLD_SLOT=$(bash deploy/scripts/current-slot.sh)

if [ "$NEW_SLOT" = "$OLD_SLOT" ]; then
    echo "WARNING: $NEW_SLOT is already active. Nothing to do."
    exit 0
fi

# Project names для изоляции слотов (compose не трогает контейнеры другого проекта)
PROJECT_NAME_OLD=$(get_project_name "$OLD_SLOT")
PROJECT_NAME_NEW=$(get_project_name "$NEW_SLOT")
COMPOSE_APP_OLD="$DEPLOY_DIR/docker-compose.app.${OLD_SLOT}.yml"
COMPOSE_APP_NEW="$DEPLOY_DIR/docker-compose.app.${NEW_SLOT}.yml"

echo "=== Switching traffic: $OLD_SLOT -> $NEW_SLOT ==="
echo " Old slot project: $PROJECT_NAME_OLD"
echo " New slot project: $PROJECT_NAME_NEW"

# 1. Деактивируем старый слот: passive останавливает консьюмеры и cron, FPM продолжает обслуживать HTTP
echo "[1/7] Deactivating $OLD_SLOT (recreate with SLOT_ROLE=passive)..."
export SLOT_ROLE=passive
render_compose "$OLD_SLOT"
docker compose --env-file "$ENV_FILE" -p "$PROJECT_NAME_OLD" -f "$COMPOSE_APP_OLD" up -d --force-recreate app webserver

# 2. Убеждаемся, что консьюмеры в старом слоте действительно остановлены
echo "[2/7] Verifying $OLD_SLOT consumers stopped..."
CONSUMER_CHECK_RETRIES=10
CONSUMER_CHECK_INTERVAL=2
CONSUMERS_STOPPED=false

for i in $(seq 1 $CONSUMER_CHECK_RETRIES); do
    CONSUMER_STATUS=$(docker exec ${OLD_SLOT}-app supervisorctl status 2>/dev/null || echo "ERROR")
    # grep -c при отсутствии совпадений возвращает exit 1 — || true защищает от set -e
    RUNNING_CONSUMERS=$(echo "$CONSUMER_STATUS" | grep -E "consumer-|deliver-news" | grep -c "RUNNING" || true)
    if [ -z "$RUNNING_CONSUMERS" ] || [ "$RUNNING_CONSUMERS" = "0" ]; then
        echo "+++ All consumers in $OLD_SLOT stopped (attempt $i/$CONSUMER_CHECK_RETRIES)"
        CONSUMERS_STOPPED=true
        break
    fi
    echo "!!! $RUNNING_CONSUMERS consumers still running in $OLD_SLOT (attempt $i/$CONSUMER_CHECK_RETRIES), retrying in ${CONSUMER_CHECK_INTERVAL}s..."
    sleep $CONSUMER_CHECK_INTERVAL
done

if [ "$CONSUMERS_STOPPED" = "false" ]; then
    echo "--- CRITICAL: Consumers in $OLD_SLOT did not stop after $CONSUMER_CHECK_RETRIES attempts"
    echo "Aborting switch to prevent dual-active slots"
    exit 1
fi

# 3. Активируем новый слот: запускает консьюмеры и cron, FPM уже работал в passive
echo "[3/7] Activating $NEW_SLOT (recreate with SLOT_ROLE=active)..."
export SLOT_ROLE=active
render_compose "$NEW_SLOT"
docker compose --env-file "$ENV_FILE" -p "$PROJECT_NAME_NEW" -f "$COMPOSE_APP_NEW" up -d --force-recreate app webserver

# Даём контейнерам время на инициализацию FPM + supervisor
sleep 5

# 4. Переключаем switch-nginx — трафик идёт на новый слот
echo "[4/7] Switching nginx upstream..."
CONF_FILE="$DEPLOY_DIR/deploy/switch-nginx/default.conf"
sed -i "s/${OLD_SLOT}-webserver/${NEW_SLOT}-webserver/" "$CONF_FILE"
docker exec switch-nginx nginx -s reload

# 5. Проверяем через switch-nginx с ретри
echo "[5/7] Verifying switch via switch-nginx..."
VERIFY_RETRIES=10
VERIFY_INTERVAL=3
VERIFY_OK=false

for i in $(seq 1 $VERIFY_RETRIES); do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ready 2>/dev/null || echo "000")
    if [ "$HTTP_CODE" = "200" ]; then
        echo "+++ Switch-nginx health check passed (attempt $i/$VERIFY_RETRIES)"
        VERIFY_OK=true
        break
    fi
    echo "!!! Attempt $i/$VERIFY_RETRIES: switch-nginx returned HTTP $HTTP_CODE, retrying in ${VERIFY_INTERVAL}s..."
    sleep $VERIFY_INTERVAL
done

if [ "$VERIFY_OK" = "false" ]; then
    echo "--- CRITICAL: Post-switch health check failed! HTTP $HTTP_CODE"
    echo "Rolling back..."
    # Возвращаем nginx на старый слот
    sed -i "s/${NEW_SLOT}-webserver/${OLD_SLOT}-webserver/" "$CONF_FILE"
    docker exec switch-nginx nginx -s reload
    # Реактивируем старый слот
    export SLOT_ROLE=active
    render_compose "$OLD_SLOT"
    docker compose --env-file "$ENV_FILE" -p "$PROJECT_NAME_OLD" -f "$COMPOSE_APP_OLD" up -d --force-recreate app webserver
    # Деактивируем новый
    export SLOT_ROLE=passive
    render_compose "$NEW_SLOT"
    docker compose --env-file "$ENV_FILE" -p "$PROJECT_NAME_NEW" -f "$COMPOSE_APP_NEW" up -d --force-recreate app webserver
    echo "Rolled back to $OLD_SLOT (NEW slot $NEW_SLOT deactivated)"
    exit 1
fi

# 6. Обновляем state-файл
echo "[6/7] Updating state..."
echo "$NEW_SLOT" > "$STATE_FILE"

# 7. Готово
echo "[7/7] Switch complete!"

echo "+++ Traffic switched: $OLD_SLOT -> $NEW_SLOT"
echo "Old slot $OLD_SLOT is in PASSIVE mode (containers still running)"
echo "To clean up: bash scripts/cleanup-slot.sh $OLD_SLOT"
