version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php1
      - php2

  php1:
    build: ./php
    depends_on:
      - redis

  php2:
    build: ./php
    depends_on:
      - redis

  redis:
    build: ./redis