services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude:
      - '../src/Kernel.php'
      - '../src/Domain/Entity/'
      - '../src/Domain/ValueObject/'

  App\Domain\Factory\NewsFactoryInterface:
    alias: App\Infrastructure\Factory\NewsFactory
