services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude:
      - '../src/Kernel.php'
      - '../src/Domain/Entity/'
      - '../src/Domain/ValueObject/'

  App\Domain\Factory\NewsFactoryInterface:
    alias: App\Infrastructure\Factory\NewsFactory

  App\Application\UseCase\NewsMetadataProvider\NewsMetadataProviderInterface:
    alias: App\Infrastructure\Service\HtmlNewsMetadataProvider

  App\Domain\Repository\NewsRepositoryInterface:
    alias: App\Infrastructure\Repository\DoctrineNewsRepository

#  App\Domain\Repository\NewsRepositoryInterface:
#    alias: App\Infrastructure\Repository\FileNewsRepository
