; Дублирование сообщений Max->Telegram
[program:telegram_forward_consumer]
command=php /data/bin/consumer-telegram-forward.php
autostart=true
autorestart=true
stdout_logfile=/var/log/app/consumer_telegram_forward.out.log
stderr_logfile=/var/log/app/consumer_telegram_forward.err.log
stopwaitsecs=10
