; Доставка новостей подписчикам
[program:news_delivery_consumer]
command=php /data/bin/consumer-news-delivery.php
autostart=true
autorestart=true
stderr_logfile=/var/log/app/consumer_news_delivery.err.log
stdout_logfile=/var/log/app/consumer_news_delivery.out.log
stopwaitsecs=10
