[program:php_fpm]
command=php-fpm --nodaemonize
autostart=true
autorestart=true
stdout_logfile=/var/log/app/php-fpm.out.log
stderr_logfile=/var/log/app/php-fpm.err.log
stopsignal=QUIT
stopwaitsecs=30
