FROM nginx

WORKDIR /app

VOLUME /app

RUN rm /etc/nginx/conf.d/default.conf

COPY ./hosts/nginx-balancer.conf /etc/nginx/conf.d/nginx-balancer.conf

EXPOSE 80
EXPOSE 6379

CMD ["nginx", "-g", "daemon off;"]