upstream php-fpm-backend {
    # least_conn;
    # ip_hash;
    server php_course_php_fpm1:9000; # weight=5 fail_timeout=2;
    server php_course_php_fpm2:9000;
    server php_course_php_fpm3:9000;
}

server {
    # слушаем стандартный порт для http-запросов
    listen 80 default_server;

    # _ - служебное имя сервера: обрабатываем все запросы с любым Host к веб-серверу
    server_name _;

    # корневая директория с файлами
    root /var/www/php_course;

    # стартовый файл, к которому веб-сервер будет обращаться по умолчанию
    index index.php;

    # Все 404 ошибки обрабатываем через index.php (внутренний редирект)
    error_page 404 = /index.php;

    # Обращения к статическим файлам логировать не будем.
    # В кэше будем хранить эти файлы максимальное время
    location ~* .(jpg|jpeg|gif|png|css|js|ico|html)$ {
        access_log off;
        expires max;
    }

    # Единая точка входа. Все запросы к веб-серверу будут направляться в корневую директорию
    # хоста ( / ) в файл index.php
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Обращения к php-fpm
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-fpm-backend;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    # при попытке прямого обращения к файлам *.php будем отдавать 404 ошибку
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
