upstream app-backend {
    least_conn;
#     ip_hash;
    server app1:9000;
    server app2:9000 weight=10 fail_timeout=2;
}

server {
    #   слушаем стандартный порт для http-запросов
    listen 80;

    #   _ - служебное имя сервера: обрабатываем все запросы с любым Host к веб-серверу
    server_name _;

    root /data/mysite.local;

    index index.php;

    #   обращения к статическим файлам логировать не будем, в кэше будем хранить
    #   максимальное время
    location ~* .(jpg|jpeg|gif|png|css|js|ico|html)$ {
        access_log off;
        expires max;
    }

    #   Единая точка входа. Все запросы к веб-серверу будут направляться в корневую директорию
    #   хоста ( / ) в файл index.php
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    #   Обращения к php-fpm
    location ~ ^/index\.php(/|$) {

        fastcgi_pass app-backend;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    error_page 404 =403 /;

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
