CREATE TABLE Cinema (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address TEXT NOT NULL
);

CREATE TABLE Hall (
    id SERIAL PRIMARY KEY,
    cinema_id INTEGER NOT NULL REFERENCES Cinema(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    capacity INTEGER NOT NULL
);

CREATE TABLE Seat (
    id SERIAL PRIMARY KEY,
    hall_id INTEGER NOT NULL REFERENCES Hall(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    seat_number INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('standard', 'vip', 'disabled'))
);

CREATE TABLE Movie (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    duration INTEGER NOT NULL,
    rating VARCHAR(10)
);

CREATE TABLE Session (
    id SERIAL PRIMARY KEY,
    movie_id INTEGER NOT NULL REFERENCES Movie(id) ON DELETE CASCADE,
    hall_id INTEGER NOT NULL REFERENCES Hall(id) ON DELETE CASCADE,
    start_time TIMESTAMP NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    format VARCHAR(10) NOT NULL CHECK (format IN ('2D', '3D', 'IMAX'))
);

CREATE TABLE Client (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20)
);

CREATE TABLE Ticket (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES Session(id) ON DELETE CASCADE,
    seat_id INTEGER NOT NULL REFERENCES Seat(id) ON DELETE CASCADE,
    client_id INTEGER NOT NULL REFERENCES Client(id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL,
    purchase_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
