<?php

namespace App\controllers;


class adminController extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function indexAction()
    {
        $bd = $this->bd();
        $query = array('*');
        $data = $bd->select('deli',$query);

        $this->view->render('Admin',compact('data'));
    }

    public function helloAction(){
       $data = $_POST;
       $this->view->render('Admin', compact('data'));
    }

   public function updateAction($val){
// создаем запросы
       $customer = 'booking inner join customer using(id_customer)';
       $query1 = array('id_customer as id','date','name','s_name','phone');

       $delivery = 'booking inner join delivery using(id_delivery)';
       $query2 = array('id_delivery as id','name','phone','address','notes');

       $product = 'booking inner join product_booking using(id_booking)
                           inner join product using(id_product)
                           inner join incoming using(id_incoming)
                           inner join producer using(id_producer)';
       $query3 = array("concat(producer.name,' ', product.model) as tovar","incoming.price + product.price as cost",
                       "warranty_period as warranty","product_booking.quantity as quantity");
// получаем данные из БД
       $bd = $this->bd();
        $customer   = array_pop($bd->select($customer,$query1,['id_booking' => $val]));
        $delivery   = array_pop($bd->select($delivery,$query2,['id_booking' => $val]));
        $product    = $bd->select($product,$query3,['id_booking' => $val]);
// выводим на странице
        $this->view->render('index_page');
        $this->view->renderPartial('partials/update_booking',compact('customer','delivery','product'));
   }

    /**
     * @param $table
     * @param $id
     * обновляем данные
     */

    public function setAction($table,$id)
    {
        if(isset($_POST) and !is_null($_POST)){
            $params =  $_POST;
            $where = ['id_'. $table => $id];
        } else{
            echo "В массиве пост ничего нет";
            die();
        }
        $this->bd()->update($table,$params,$where);
    }

    public function deleteAction($id){
        $table = 'product_booking';
        $this->bd()->delete($table,['id_booking'=>$id, 'id_product'=>$_POST['product']]);
        $this->redirect("http://new/admin");
    }

    public function bd()
    {
        return parent::bd(); // TODO: Change the autogenerated stub
    }

}