events { worker_connections 1024; }

http {
    upstream my_nodes {
        server nginx-1:80;
        server nginx-2:80;
    }

    server {
        listen 80;
        server_name _; # Слушать любой запрос на 80 порту

        location / {
            proxy_pass http://my_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
