doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            context_task:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/ORM/Mapping/Task'
                prefix: 'App\Domain\Task'
                alias: 'App\Domain\Task'
        controller_resolver:
            auto_mapping: false

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
