doctrine:
  dbal:
    connections:
      default:
        driver: pdo_pgsql
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        use_savepoints: true
        profiling_collect_backtrace: '%kernel.debug%'
    default_connection: default
    types:
      link: App\News\Infrastructure\Database\Type\LinkType
      title: App\News\Infrastructure\Database\Type\TitleType

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      News:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/News/Infrastructure/Database/ORM'
        prefix: 'App\News\Domain\Entity'
        alias: News

#when@test:
#  doctrine:
#    dbal:
#      # "TEST_TOKEN" is typically set by ParaTest
#      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
#
#when@prod:
#  doctrine:
#    orm:
#      auto_generate_proxy_classes: false
#      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#      query_cache_driver:
#        type: pool
#        pool: doctrine.system_cache_pool
#      result_cache_driver:
#        type: pool
#        pool: doctrine.result_cache_pool
#
#  framework:
#    cache:
#      pools:
#        doctrine.result_cache_pool:
#          adapter: cache.app
#        doctrine.system_cache_pool:
#          adapter: cache.system
