nelmio_api_doc:
    documentation:
        info:
            title: News site
            description: News site for creating and viewing news, as well as creating subscriptions to news
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
