# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
  adapters:
    upload_reports_adapter:
      local:
        location: '%kernel.project_dir%/%report_upload%'

  filesystems:
    upload_reports:
      adapter: upload_reports_adapter

