CREATE SCHEMA cinema_eav;
SET search_path TO cinema_eav;

CREATE TABLE movie (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    year SMALLINT NOT NULL CHECK (year BETWEEN 1900 AND 2100),
    CONSTRAINT unique_movie UNIQUE (name, year)
);

CREATE TYPE attribute_data_type AS ENUM ('text', 'boolean', 'date', 'integer', 'float');
CREATE TABLE attribute_type (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(255) NOT NULL UNIQUE,
    data_type attribute_data_type NOT NULL
);

CREATE TABLE attribute (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    attribute_name VARCHAR(255) NOT NULL UNIQUE,
    attribute_type_id INT NOT NULL,
    FOREIGN KEY (attribute_type_id) REFERENCES attribute_type (id)
);

CREATE TABLE attribute_value (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    movie_id INT NOT NULL,
    attribute_id INT NOT NULL,
    text_value TEXT DEFAULT NULL,
    boolean_value BOOLEAN DEFAULT NULL,
    date_value DATE DEFAULT NULL,
    integer_value INT DEFAULT NULL,
    float_value REAL DEFAULT NULL,
    FOREIGN KEY (movie_id) REFERENCES movie (id),
    FOREIGN KEY (attribute_id) REFERENCES attribute (id),
    CONSTRAINT all_values_is_null_except_one CHECK (
        num_nonnulls(text_value, boolean_value, date_value, integer_value, float_value) = 1
    )
);

CREATE INDEX idx_attribute_attribute_type_id ON attribute (attribute_type_id);
CREATE INDEX idx_attribute_value_movie_id ON attribute_value (movie_id);
CREATE INDEX idx_attribute_value_attribute_id ON attribute_value (attribute_id);
CREATE INDEX idx_attribute_value_text_value ON attribute_value (text_value) WHERE text_value IS NOT NULL;
CREATE INDEX idx_attribute_value_boolean_value ON attribute_value (boolean_value) WHERE boolean_value IS NOT NULL;
CREATE INDEX idx_attribute_value_date_value ON attribute_value (date_value) WHERE date_value IS NOT NULL;
CREATE INDEX idx_attribute_value_integer_value ON attribute_value (integer_value) WHERE integer_value IS NOT NULL;
CREATE INDEX idx_attribute_value_float_value ON attribute_value (float_value) WHERE float_value IS NOT NULL;
