version: '3'

services:
  db:
    image: postgres:15.5
    container_name: hw9-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - otus-network

volumes:
  pgdata:

networks:
  otus-network:
    driver: bridge
