FROM php:8.2-fpm-alpine

# Install dependencies
RUN apk add --no-cache \
    mongo-c-driver-dev \
    openssl-dev \
    pcre-dev \
    autoconf \
    g++ \
    make \
    libzip-dev \
    zlib-dev \
    libmemcached-dev \
    libpng-dev \
    oniguruma-dev

# Install PHP extensions
RUN docker-php-ext-install \
    pdo_mysql \
    mysqli \
    mbstring \
    zip \
    gd \
    opcache

# Install Redis extension
RUN pecl install redis && docker-php-ext-enable redis \
    && pecl install mongodb && docker-php-ext-enable mongodb

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html